[sideupload]
listenPort = 8888
targetDir = "./samples/storage_object"
cronWithSecond = "0 0 12 * * *"
storageDays = 10

[sideupload.backupStorage]
customEndpoint = ""
region = "us-west-2"
bucketName = "/sideupload"
prefix = ""
accessKey = "minio"
SecretKey = "minio_good_secretkey"
